PROJECT_NAME = "JAGER"
VERSION = "0.4.0"

STATUS_NORMAL = "NORMAL"
STATUS_DEGRADED = "DEGRADED"
STATUS_FAILED = "FAILED"

DECISION_ALLOW = "ALLOW"
DECISION_DENY = "DENY"

STRATEGY_EXPLORE = "EXPLORE"
STRATEGY_EXPLOIT = "EXPLOIT"

DEFAULT_SEED = 42
DEFAULT_BUDGET = 1000
